version: "3"
services:      
  postgres:
    container_name: postgres_nest_rest
    image: postgres:14.5
    ports:
    - "5432:5432"
    volumes:
    - postgresdata:/data/postgres14
    - postgresdbdata:/var/lib/postgresql14/data
    env_file:
    - docker.env

volumes:
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local